codecov:
  notify:
    require_ci_to_pass: yes
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: yes

parsers:
  javascript:
    enable_partials: true

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
